# Action name
name: Docker Build and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner or OS that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        # checkout our code to be used as refrence code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        # QEMU -> Quick EMUlator
        # QEMU will create execution environment and enable the execution of different multi-architecture containers
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        # will create and boot a builder using by default the docker-container builder driver
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        #  will take care to log in against a Docker registry.
        uses: docker/login-action@v1 
        with:
          # get the credential using github secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        # will push our already built image to our Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: repoerna/python-helloworld:latest